# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  DENO_VERSION: "v1.32.3"
  TS_VERSION: "5.0.3"
  
pool:
  vmImage: ubuntu-latest

steps:
  - bash: curl -L https://deno.land/x/install/install.sh | sh -s $(DENO_VERSION)
  - bash: echo '##vso[task.prependpath]$(HOME)/.deno/bin/'
  - script: $(HOME)/.deno/bin/deno run --allow-all test.ts
