// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/api/routes.ts";
import * as $2 from "./routes/api/weather.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/Header.tsx";
import * as $$1 from "./islands/Submit.tsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/api/routes.ts": $1,
    "./routes/api/weather.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/Header.tsx": $$0,
    "./islands/Submit.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
